version: '3'
services:
  mysql:
    image: mysql:5.7
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./db/mysql:/var/lib/mysql
  dev:
    image: teanoon/java-dev
    environment:
      DISPLAY: $DISPLAY
      http_proxy: "http://172.99.0.1:8123"
      https_proxy: "http://172.99.0.1:8123"
    volumes:
      - .:/code
      - .IdeaIC2017.1:/home/dev/.IdeaIC2017.1
      - .IdeaIC.java:/home/dev/.java
      - .gradle:/home/dev/.gradle
      - .zsh_history:/home/dev/.zsh_history
      - .zshrc:/home/dev/.zshrc
      - ~/.ssh:/home/dev/.ssh
      - /boxes/idea:/home/dev/idea
      - /tmp/.X11-unix:/tmp/.X11-unix
    links:
      - mysql
