spring:
    jpa.hibernate.ddl-auto: validate
    jpa.properties.hibernate.enable_lazy_load_no_trans: true
    datasource:
        url: jdbc:mysql://localhost/research?useSSL=false
        username: root
logging.level.: info
